spring:
  application:
    name: MultifunctionalProject
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver